-- MySQL Script generated by MySQL Workbench
-- 04/01/18 18:57:08
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Bestellung`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bestellung` (
  `Bestellungs-ID` INT NOT NULL,
  `Kunden-ID` INT NULL,
  `Bestellungsdatum` DATETIME NULL,
  `Lieferdatum` DATETIME NULL,
  PRIMARY KEY (`Bestellungs-ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Kunden`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Kunden` (
  `Kunden-ID` INT NOT NULL,
  `Kundenname` VARCHAR(45) NULL,
  `Kundenadresse` VARCHAR(45) NULL,
  `Telefonnummer` INT NULL,
  `Bestellung_Bestellungs-ID` INT NOT NULL,
  PRIMARY KEY (`Kunden-ID`),
  INDEX `fk_Kunden_Bestellung1_idx` (`Bestellung_Bestellungs-ID` ASC),
  CONSTRAINT `fk_Kunden_Bestellung1`
    FOREIGN KEY (`Bestellung_Bestellungs-ID`)
    REFERENCES `mydb`.`Bestellung` (`Bestellungs-ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Artikel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Artikel` (
  `Artikel-ID` INT NOT NULL,
  `Artikelname` VARCHAR(45) NULL,
  `Preis` INT NULL,
  `Kategorie` VARCHAR(45) NULL,
  PRIMARY KEY (`Artikel-ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Kategorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Kategorie` (
  `Kategorie-ID` INT NOT NULL,
  `Kategoriename` VARCHAR(45) NULL,
  `Artikel_Artikel-ID` INT NOT NULL,
  PRIMARY KEY (`Kategorie-ID`),
  INDEX `fk_Kategorie_Artikel1_idx` (`Artikel_Artikel-ID` ASC),
  CONSTRAINT `fk_Kategorie_Artikel1`
    FOREIGN KEY (`Artikel_Artikel-ID`)
    REFERENCES `mydb`.`Artikel` (`Artikel-ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bestellung_has_Artikel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bestellung_has_Artikel` (
  `Bestellung_Bestellungs-ID` INT NOT NULL,
  `Artikel_Artikel-ID` INT NOT NULL,
  PRIMARY KEY (`Bestellung_Bestellungs-ID`, `Artikel_Artikel-ID`),
  INDEX `fk_Bestellung_has_Artikel_Artikel1_idx` (`Artikel_Artikel-ID` ASC),
  INDEX `fk_Bestellung_has_Artikel_Bestellung_idx` (`Bestellung_Bestellungs-ID` ASC),
  CONSTRAINT `fk_Bestellung_has_Artikel_Bestellung`
    FOREIGN KEY (`Bestellung_Bestellungs-ID`)
    REFERENCES `mydb`.`Bestellung` (`Bestellungs-ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bestellung_has_Artikel_Artikel1`
    FOREIGN KEY (`Artikel_Artikel-ID`)
    REFERENCES `mydb`.`Artikel` (`Artikel-ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
